services:

  spark-master:
    # Python 3.10
    image: custom/spark:3.5.5-scala2.12-java17-python3-ubuntu
    container_name: spark-master
    ports:
      - "8082:8080"  # Spark Master UI
      - "7077:7077"
    environment:
      - SPARK_MODE=master
      # Hadoop
      - HADOOP_USER_NAME=hadoopuser
      # Deequ
      - SPARK_VERSION=3.5.5
      # MinIO
      - MINIO_ACCESS_KEY=lLZ6r6vDyQvxq5WaTJ9w
      - MINIO_SECRET_KEY=WkxauVOq61tg0DnFQNSNnI8TbKfl9qxHBK3zILZ8
    volumes:
      - ./config/spark-master.conf:/opt/spark/conf/spark-defaults.conf
    networks:
      - hadoop_default

  spark-history:
    image: custom/spark:3.5.5-scala2.12-java17-python3-ubuntu
    ports:
      - "18080:18080"
    environment:
      - SPARK_MODE=history
      # Hadoop
      - HADOOP_USER_NAME=hadoopuser
      # Deequ
      - SPARK_VERSION=3.5.5
      # MinIO
      - MINIO_ACCESS_KEY=lLZ6r6vDyQvxq5WaTJ9w
      - MINIO_SECRET_KEY=WkxauVOq61tg0DnFQNSNnI8TbKfl9qxHBK3zILZ8
    volumes:
      - ./config/spark-history.conf:/opt/spark/conf/spark-defaults.conf
    networks:
      - hadoop_default

  spark-worker-1:
    image: custom/spark:3.5.5-scala2.12-java17-python3-ubuntu
    depends_on:
      - spark-master
    ports:
      - "8081:8081" # Worker 1 UI
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=16
      - SPARK_LOCAL_DIRS=/opt/spark/tmp
      # Hadoop
      - HADOOP_USER_NAME=hadoopuser
      # Deequ
      - SPARK_VERSION=3.5.5
      # MinIO
      - MINIO_ACCESS_KEY=lLZ6r6vDyQvxq5WaTJ9w
      - MINIO_SECRET_KEY=WkxauVOq61tg0DnFQNSNnI8TbKfl9qxHBK3zILZ8
    volumes:
    #   - sparktmp-data:/opt/spark/tmp
      - /media/ad/hdd4tb/data/TPC-H/300GB:/opt/spark/work-dir/tpch:readonly
    networks:
      - hadoop_default

# volumes:
#   sparktmp-data:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: /media/ad/hdd4tb/docker/volumes/spark/sparktmp-data

networks:
  # Use a pre-existing network
  hadoop_default:
    external: true