services:
  minio:
    image: minio/minio:latest
    ports:
      # API
      - 29000:9000
      # console
      - 29001:9001
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=adminpassword
    volumes:
      - minio_data:/data
    command: minio server /data --console-address ":9001"
    networks:
      - hadoop_default

volumes:
  minio_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /media/ad/hdd4tb/docker/volumes/minio

networks:
  # Use a pre-existing network
  hadoop_default:
    external: true