version: "3.9"  # Or a compatible version

services:
  tpchpostgres:
    image: postgres:15 # Or specify your desired PostgreSQL version (e.g., postgres:14, postgres:13)
    ports:
      - "5432:5432"  # Map the container's port 5432 to your host's port 5432. Change the host port if needed.
    environment:
      POSTGRES_USER: tpch_user  # Set the PostgreSQL user
      POSTGRES_PASSWORD: tpch_password  # Set the PostgreSQL password (IMPORTANT: Use a strong password in production)
      POSTGRES_DB: tpch_db  # Set the database name
    volumes:
      - .:/tpch
      - tpch_postgres_data:/var/lib/postgresql/data  # Persist data across container restarts (Highly recommended!)
      - ./my-postgres.conf:/var/lib/postgresql/data/postgresql.conf # custom Postgres conf
    restart: unless-stopped  # Ensure the container restarts if there's an issue
    networks:
      - hadoop_default
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: mypgadminpassword
    ports:
      - "28080:80"  
    networks:
      - hadoop_default

volumes:
  tpch_postgres_data:  # Named volume for data persistence
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /media/ad/hdd4tb/docker/volumes/tpch-postgres


networks:
  # Use a pre-existing network
  hadoop_default:
    external: true